name: Build AHQ AI Server

on:
  create:
    branches:
      - server-v*
  push:
    branches:
      - main
    paths:
      - serverMatrix.cjs
      - server/**
      - .github/workflows/server.yml
      - .github/workflows/pages.yml
      - genServerTag.ps1
      - keygen/**
      - getllamacpp/**
      - ahqrt/**
      - prebuild.ps1

permissions: write-all

jobs:
  create:
    name: Create Release

    outputs:
      matrix: ${{ steps.matrices.outputs.result }}
      upload_url: ${{ steps.rel.outputs.upload_url }}
      release_id: ${{ steps.rel.outputs.id }}
      app_version: ${{ steps.tag.outputs.abs }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v5

      - name: Get Tag Data
        shell: pwsh
        id: tag
        run: |
          ./genServerTag.ps1
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Generate Matrices
        uses: actions/github-script@v8
        id: matrices
        with:
          script: |
            const out = require("./serverMatrix.cjs");

            return out();

      - name: Generate Cryptographically Safe Public Key
        run: |
          npm i -g pnpm
          pnpm install
          node crypto.js
        env:
          ALPHA: ${{ github.ref_name == 'main' }}
          MONGODB: ${{ secrets.MONGODB_CREDENTIALS }}
          SEED: ${{ secrets.SERVER_INTEGRITY_SEED }}
          VERSION: ${{ steps.tag.outputs.abs }}
        working-directory: keygen

      - name: Request re-building of site
        uses: actions/github-script@v7
        with:
          script: |
            await octokit.rest.actions.createWorkflowDispatch({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.repository }}".split("/")[1],
              workflow_id: 227024493,
              ref: "main"
            });

      - name: Release
        uses: softprops/action-gh-release@v2
        id: rel
        with:
          name: AHQ AI Server ${{ steps.tag.outputs.out }}
          body_path: ./RELEASE_SERVER.md
          append_body: true
          generate_release_notes: true
          tag_name: ${{ steps.tag.outputs.tag }}
          prerelease: ${{ github.ref_name == 'main' }}
          make_latest: false
          draft: true

  build:
    name: Build Server

    needs: [create]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        include: ${{ fromJson(needs.create.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          components: rustfmt
          rustflags: ${{ matrix.rustflags }}

      - name: Setup NodeJS
        uses: actions/setup-node@v5

      - name: Generate Cryptographically Safe Public Key
        run: |
          npm i -g pnpm
          pnpm install
          node crypto.js
        env:
          SEED: ${{ secrets.SERVER_INTEGRITY_SEED }}
          VERSION: ${{ needs.create.outputs.app_version }}
        working-directory: keygen

      - name: Build Server
        shell: pwsh
        run: |
          ./prebuild.ps1
        env:
          SUFFIX: ${{ matrix.end }}
          ALLOC: ${{ matrix.allocator }}
          TARGET: ${{ matrix.target }}
          VERSION: ${{ needs.create.outputs.app_version }}

      - name: Upload Binaries
        uses: AButler/upload-release-assets@v3.0
        with:
          files: |
            ahqai-server*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-id: ${{ needs.create.outputs.release_id }}

  publish:
    name: Publish release

    needs: [create, build]
    if: success()

    runs-on: ubuntu-latest

    steps:
      - name: Undraft Release
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.repository }}".split("/")[1],
              release_id: ${{ needs.create.outputs.release_id }},
              draft: false
            });

  delete:
    name: Delete release in failure

    needs: [create, build]
    if: failure()

    runs-on: ubuntu-latest

    steps:
      - name: Delete Release
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.repos.deleteRelease({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.repository }}".split("/")[1],
              release_id: ${{ needs.create.outputs.release_id }}
            });
